[이진우] sprint9
codeit-sprint-fullstack/1-Sprint-Mission-FE pull request #135
Opened 2024-09-22 10:05 UTC by ajantang

## 요구사항

### 기본

- [x]
- []
- []

### 심화

- [x]
- []

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-09-25 14:51 UTC, wildCodingWarrior requested changes
고생하셨습니다 ! 점점 나아지는게 느껴지네요. 커스텀 훅만 더 활용 잘 해봅시다.

2024-09-25 14:51 UTC, wildCodingWarrior commented on app/bulletin-board/BestBoard.js
> +  );
관리하기에 이게 더 좋네요. classNames 라이브러리

2024-09-25 14:51 UTC, wildCodingWarrior commented on app/bulletin-board/BestBoard.js
> +  );
P3
await와 then을 혼용하고 있습니다. 일관성을 위해 하나의 방식만 사용하는 것이 좋습니다.

2024-09-25 14:51 UTC, wildCodingWarrior commented on app/bulletin-board/BestBoard.js
> +  );
P3
map 함수에서 index를 key로 사용하는 것은 권장되지 않으니, 대신 고유한 id를 사용하세요.

2024-09-25 14:51 UTC, wildCodingWarrior commented on app/bulletin-board/Board.js
P4
보통 스크롤 위치로 판별하기보다는 intersection observer를 많이 사용합니다. 한 번 알아보시는 걸 권장드립니다.

2024-09-25 14:51 UTC, wildCodingWarrior commented on app/components/CommentSection.js
> +    mutationFn: ({ postId, content }) => createPostComment(postId, content),
P3
사사롭지만 타입스크립트까지 적용하게 될 무렵에는 {postId, content} 이런식으로 파라미터를 객체로 넣는 방식을 권장합니다.

2024-09-25 14:51 UTC, wildCodingWarrior commented on app/components/EmailInput.js
> +}
P4
전체적으로 form을 구현하기 쉽지 않은 부분 중 하나인데, 이 부분 나중에 react-hook-form 한번 알아보시면 좋을 것 같아요.

2024-09-25 14:51 UTC, wildCodingWarrior commented on app/components/HeaderUser.js
> +  );
P2
가독성 측면에서 result로 만들기보다는 JSX return 하는 곳에서 곧바로 사용하는게 더 좋겠습니다.

2024-09-25 14:51 UTC, wildCodingWarrior commented on app/items/[productId]/page--client.js
> +  }, []);
따로 state 여러개 안 만들고 하나의 product 객체를 담는 state를 만들면 어떨까요?

2024-09-25 14:51 UTC, wildCodingWarrior commented on lib/api-post.js
> +
아주 좋은 테크닉이네요.

2024-09-25 14:51 UTC, wildCodingWarrior commented on lib/api-post.js
> +export async function getPosts(page, pageSize, orderBy, keyword) {
P3
이런식으로 파라미터가 여러개 있는 곳은 항상 객체로 params 받아주는게 좋습니다.

2024-09-25 14:51 UTC, wildCodingWarrior commented on app/components/EmailInput.js
> +}
아 이미 활용하셨군요

2024-09-29 13:42 UTC, ajantang commented on app/components/HeaderUser.js
> +  );
수정 완료

2024-09-29 13:44 UTC, ajantang commented on app/bulletin-board/BestBoard.js
> +  );
then을 선호하는 편입니다. 어느 순간 await를 쓰는 부분이 있는데, 이 부분은 수정해두겠습니다

2024-10-02 13:50 UTC, wildCodingWarrior approved these changes
배포하신 주소 살펴보니 상세 페이지는 접속이 불가능하네요. 하지만 늘 그렇듯이 전체적으로 고민을 많이 하신 흔적이 보이는 코드입니다. 점점 더 코드가 깔끔해지는 것이 느껴지네요.

404 에러의 경우에는 실제로 같이 테스트를 해봐야 해결 할 수 있을 것 같은데, 멘토링 30분 진행하고 남은 시간에 같이 문제 해결해 보면 좋겠습니다.

2024-10-02 13:50 UTC, wildCodingWarrior commented on app/items/[productId]/DropDownKebabProduct.js
> +    </>
간단한 로직이라면 그냥 이런식으로 곧바로 작성해도 무방하다고 생각합니다.

다만 react에서 제공하는 createPortal 사용해도 괜찮았을 것 같네요

2024-10-02 13:50 UTC, wildCodingWarrior commented on app/hooks/useAuth.js
> +      };
로그인에 해당하는 이 부분은 
https://zustand.docs.pmnd.rs/integrations/persisting-store-data
여기 있는 미들웨어 활용하는게 사용자 경험에 훨씬 도움이 되겠습니다.

2024-10-02 13:50 UTC, wildCodingWarrior commented on lib/axios-codeit-token.js
> +);
활용이 아주 좋네요

2024-10-02 13:50 UTC, wildCodingWarrior commented on vercel.json
> +}
404 에러가 이거랑 관련되어 있을 가능성이 높습니다. 이건 왜 있는 코드인가요?

2024-10-02 13:50 UTC, wildCodingWarrior commented on lib/api-codeit-user.js
>      throw err;
이 파일 이름들 굳이 api라는 이름을 파일명에 안 붙이고 폴더에 정리하는게 더 깔끔할 것 같습니다.

2024-10-02 13:50 UTC, wildCodingWarrior commented on app/sign-up/SignUpSet.js
>          })}
오타겠죠? 닉네임가

2024-10-02 13:50 UTC, wildCodingWarrior commented on app/items/[productId]/ProductImageListSet.js
> +      });
이 부분 불필요하지 않나요?

2024-10-06 11:02 UTC, merged