[박명준] Sprint9
codeit-sprint-fullstack/1-Sprint-Mission-FE pull request #146
Opened 2024-09-24 00:38 UTC by mjpark-k

## 요구사항

## 기본 요구사항

### 공통

- [x] Github에 위클리 미션 PR을 만들어 주세요.
- [x] React 혹은 Next.js를 사용해 진행합니다.
- [x] 프론트엔드에서 api 요청 구현은 TanStack React Query를 활용해 주세요.
- [x] API는 https://panda-market-api.vercel.app 를 사용합니다. 명세는 https://panda-market-api.vercel.app/docs 를 확인해 주세요.

**로그인/회원가입 페이지**

- [x] JavaScript로 구현한 로그인/회원가입 페이지를 React.js 혹은 Next.js로 마이그레이션해 주세요.

**로그인 페이지**

- [x] "회원 가입하기"를 클릭하면 회원가입 페이지로 이동해 주세요.
- [x] 로그인 실패하는 경우, 이메일 input 아래에 "이메일을 확인해 주세요.", 비밀번호 input 아래에 "비밀번호를 확인해 주세요." 에러 메시지를 표시해 주세요.
- [x] 로그인 버튼이 활성화된 후, 로그인 버튼 클릭 또는 Enter키 입력으로 로그인 실행합니다.
- [x] "/api/signIn"으로 POST 요청해서 성공 응답을 받으면 중고 마켓 페이지로 이동합니다. 참고로 JWT로 구현되어 있습니다.
- [x] 실패할 경우, 실패 메시지를 모달을 통해 표시합니다.

**회원가입 페이지**

- [x] "회원 가입하기"를 클릭하면 '/signin' 페이지로 이동합니다
- [x] 회원가입 버튼 클릭 또는 Enter키 입력으로 회원가입을 실행합니다.
- [x] 비밀번호 input과 비밀번호 확인 input의 값이 다른 경우, 비밀번호 확인 input 아래에 "비밀번호가 일치하지 않아요." 에러 메시지를 표시해 주세요.
- [x] 버튼이 활성화된 후, 회원가입은 "/api/signUp" POST 요청해서 진행합니다. 참고로 JWT로 구현되어 있습니다.
- [x] 회원가입 성공 응답을 받으면 중고마켓 페이지로 이동합니다.
- [x] 실패할 경우, 실패 메시지를 모달을 통해 표시합니다.

**로그인, 회원가입 페이지 공통**

- [x] 눈 모양 아이콘 클릭 시 비밀번호의 문자열이 보이기도 하고, 가려집니다.
- [x] 비밀번호의 문자열이 가려질 때는 눈 모양 아이콘에는 사선이 그어져 있고, 비밀번호의 문자열이 보일 때는 사선이 없는 눈 모양 아이콘이 보입니다.
- [x] 소셜 로그인에 구글 아이콘 클릭 시 'https://www.google.com', 카카오 아이콘 클릭 시 'https://www.kakaocorp.com/page'로 이동합니다.
- [x] 로그인/회원가입 시 성공 응답으로 받은 accessToken을 로컬 스토리지에 저장합니다.
- [x] 로그인/회원가입 페이지에 접근 시 로컬 스토리지에 accessToken이 있는 경우 '/folder' 페이지로 이동합니다.

**GNB**

- [x] 상단 내비게이션 바에 프로필 영역은 인가된 경우, 유저 정보 API를 활용해 주세요.
- [x] 인가되지 않았을 경우 "로그인" 버튼이 보이게 해 주세요.

**상품 상세 페이지**

- [x] PC, Tablet, Mobile 디자인에 해당하는 상품 상세 페이지를 만들어 주세요.
- [x] 상품 상세 페이지 url path는 "/items/{itemId}"로 설정하세요.
- [x] '목록으로 돌아가기' 버튼 클릭 시 중고마켓 페이지 "/items"로 이동합니다.
- [x] 상품 상세 데이터는 '/products/{productId}' GET 메서드 사용해 불러오세요. 이때, 상품 상세 조회는 인가된 사용자만 이용할 수 있도록 합니다.
- [x] 상품에 대한 댓글 조회도 가능합니다.
- [x] 상품 수정 및 삭제 기능을 API를 활용해 구현합니다. 이때, 인가된 사용자만 이용할 수 있도록 합니다.
- [x] 상품 수정은 '/products/{productId}' PUT을 사용합니다.
- [x] 상품 삭제는 '/products/{productId}' DELETE를 사용합니다.
- [x] 상품 삭제 전, 확인 모달을 띄워주세요.
- [x] 상품에 대한 좋아요 및 좋아요 취소 기능을 https://panda-market-api.vercel.app/docs에 명세된 '/products/{productId}/favorite' POST & DELETE 활용해 구현합니다. 이때 인가된 사용자만 좋아요 기능을 이용할 수 있도록 합니다.
- [x] 댓글 생성 및 삭제 기능을 API를 활용해 구현합니다. 이때, 인가된 사용자만 이용할 수 있도록 합니다.
- [x] 댓글 수정은 https://panda-market-api.vercel.app/docs에 명세된 '/products/{productId}/comments' PUT을 사용합니다.
- [x] 댓글 삭제는 https://panda-market-api.vercel.app/docs에 명세된 '/products/{productId}/comments' DELETE를 사용합니다.

## 심화 요구사항

**로그인 및 회원가입 페이지 공통**

- [x] 로그인, 회원가입 기능에 react-hook-form을 활용해 주세요.
- [x] 브라우저에 현재 보이는 화면의 영역(viewport) 너비를 기준으로 분기되는 반응형 디자인을 적용합니다.

- PC: 1200px 이상
- Tablet: 744px 이상 ~ 1199px 이하
- Mobile: 375px 이상 ~ 743px 이하
- 375px 미만 사이즈의 디자인은 고려하지 않습니다

**유저 기능**

- [x] 리퀘스트 헤더에 인증 토큰을 첨부할 때 axios interceptors를 활용해 주세요. (axios를 사용하지 않는다면 이와 유사한 기능을 활용해 주세요.)

**React-Query로 마이그레이션**

- [x] fetch 혹은 axios로 구현된 기존의 API 요청 코드를 React-Qeury로 마이그레이션 합니다.

**로딩 및 에러 핸들링**

- [x] 로딩 인디케이터와 에러 메시지를 구현합니다.
- [x] 상품 목록 및 상품 상세 데이터를 Prefetching 합니다

**상품 데이터 캐싱 및 업데이트**

- [x] React Query의 캐싱 기능을 활용하여 데이터 로딩 시간을 최소화합니다.
- [x] 상품 목록 페이지에서 데이터의 실시간 업데이트를 위해 적절한 Query Refresh 설정을 적용합니다.

## 주요 변경사항

- 상품 등록 페이지 만들기
- Link를 이용한 페이지 이동
- BackEnd API 연결

## 스크린샷

## 멘토에게

- 아직 React를 이용할 때, 버벅거리고 애매하게 이해하고 있다는 생각이 들 때도 있는 것 같아서 좋은 참고 사이트같은게 있는지 궁금합니다..
- 처음에 데이터 받아오는게 느립니다. 개발자도구 network 부분에서 pending이 오래걸리는데(한 30초~40초?) 문제가 있을까요?

2024-09-25 15:00 UTC, wildCodingWarrior requested changes
아직 React를 이용할 때, 버벅거리고 애매하게 이해하고 있다는 생각이 들 때도 있는 것 같아서 좋은 참고 사이트같은게 있는지 궁금합니다..
-> 전 개인적으로는 정말 빠르게 알아볼 때는 이거 봅니다.
https://cheatsheets.shecodes.io/react

다만 평소에 공부를 해야한다면 당연히 공식문서 확인합니다. react는 공식 문서가 정말 잘되어있습니다.

처음에 데이터 받아오는게 느립니다. 개발자도구 network 부분에서 pending이 오래걸리는데(한 30초~40초?) 문제가 있을까요?

-> 어디에서 병목이 되는지는 정확히 자세한 분석이 필요하겠지만, 서버에서 응답이 느린 건 당장은 신경 안쓰셔도 괜찮습니다.

정말 중요한 데이터라면 나중에 SSR을 통해서 미리 서버에서 가져와서 사용하면 됩니다. 괜찮습니다. 

그 외 간단한 코드리뷰 진행했습니다. 

항상 느끼지만 코드 가독성이 참 좋습니다. 안쓰는 콘솔들만 항상 지워주세요!

2024-09-25 15:00 UTC, wildCodingWarrior commented on components/ArticleDropDown.js
> +
P2

사용하지 않는 console은 삭제해주세요

2024-09-25 15:00 UTC, wildCodingWarrior commented on lib/axios.js
> +  baseURL: "https://product-api-shiu.onrender.com",
P1

dotenv를 사용하는 환경변수를 꼭 활용해주세요

2024-09-25 15:00 UTC, wildCodingWarrior commented on pages/board/[id].js
> +//   );
P2

사용 안하는 코드는 삭제해주세요

2024-09-25 15:00 UTC, wildCodingWarrior commented on components/BestArticle.js
> +}
P3

컴포넌트 분리하기 좋은 코드입니다. 각 아티클 항목을 별도의 컴포넌트로 분리하면 가독성이 좋아집니다. 

articles가 없거나 비어있을 경우에 대한 처리도 추가하면 좋겠네요.

2024-09-30 04:58 UTC, mjpark-k commented on lib/axios.js
> +  baseURL: "https://product-api-shiu.onrender.com",
dotenv를 사용하는 걸로 바꿨습니다!!

2024-10-02 14:04 UTC, wildCodingWarrior approved these changes
시간이 부족하셔서 못 하신 부분이 많은게 조금 아쉽습니다. Next.js는 앞으로도 쭉 다루게 될 부분이니만큼 천천히 학습해봅시다!

2024-10-02 14:04 UTC, wildCodingWarrior commented on lib/axios.js
> +  baseURL: process.env.REACT_APP_API_BASE_URL,
우리가 사용하고 있는 앱이 NEXT_APP이기 때문에, REACT_APP 대신 NEXT_PUBLIC이라는 prefix를 붙여야 합니다. 

[Bundle environment variables for the browser by prefixing with NEXT_PUBLIC_](https://nextjs.org/docs/app/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser)

2024-10-04 04:34 UTC, mjpark-k commented on lib/axios.js
> +  baseURL: process.env.REACT_APP_API_BASE_URL,
수정했습니다!

2024-10-07 07:43 UTC, merged