[송영섭] sprint 1 + 2
codeit-sprint-fullstack/1-Sprint-Mission-FE pull request #20
Opened 2024-07-05 22:16 UTC by songyoungsub

## sprint 1 

### 기본 요구사항

#### 랜딩 페이지

[0]  React와 같은 UI 라이브러리를 사용하지 않고 진행합니다

[0]  PC사이즈만 고려해 주어진 디자인으로 구현합니다.

[0]  HTML, CSS 파일을 [Netlify](https://www.netlify.com/)로 배포해 주세요. (참고: https://www.codeit.kr/learn/5309)

[0]  랜딩 페이지의 url path는 루트(‘/’)로 설정합니다.

[0]  title은 “판다마켓”로 설정합니다.

[0]  “판다마켓” 로고 클릭 시 루트 페이지(‘/’)로 이동합니다.

[0]  '로그인' 버튼 클릭 시 로그인 페이지(‘/login’)로 이동합니다 (빈 페이지)

[0]  “구경하러 가기”버튼 클릭 시(’/items’)로 이동합니다. (빈 페이지)

[0]  “Privacy Policy”, “FAQ”는 클릭 시 각각 Privacy 페이지(‘/privacy’), FAQ 페이지(‘/faq’)로 이동합니다.(모두 빈 페이지)

[0]  페이스북, 트위터, 유튜브, 인스타그램 아이콘을 클릭 시 각각의 홈페이지로 새로운 창이 열리면서 이동합니다.

[0]  아래로 스크롤해도 “판다 마켓” 로고와 “로그인” 버튼이 있는 상단 내비게이션 바(Global Navigation Bar)가 최상단에 고정되게 해 주세요.

[0]  화면의 너비가 1920px 이상이면 하늘색 배경색은 너비를 꽉 채우도록 채워지고, 내부 요소들의 위치는 고정되고, 여백만 커지도록 합니다.

[0]  화면의 너비가 1920px 보다 작아질 때, “판다마켓” 로고의 왼쪽 여백 200px, “로그인" 버튼의 오른쪽 여백 200px이 유지되고, 화면의 너비가 작아질수록 두 요소 간 거리가 가까워지도록 설정합니다.

[0]  화면의 너비가 1920px 이상이면 내부에 있는 요소 간 동일한 간격을 유지하며 가운데 정렬해야 합니다.

[0]  화면의 너비가 1920px 보다 작아질 때, 최하단에 있는 “codeit-2024”의 왼쪽 여백 200px과 SNS 아이콘들의 오른쪽 여백 200px을 유지하면서 가운데 있는 “Privacy Policy”, “FAQ” 요소와 각각 동일한 간격을 유지하며 가까워져야 합니다.

[0]  클릭으로 기능이 동작해야 하는 경우, 사용자가 클릭할 수 있는 요소임을 알 수 있도록 CSS 속성 cursor: pointer로 설정합니다.

### 심화 요구사항

#### 공통

[0] reset.css를 설정해 주세요.
[x] 사용자의 브라우저 설정에 따라 기본 폰트 크기 설정이 변화함에 따라서 페이지의 요소 간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정해 주세요

## sprint 2

### 기본 요구사항

#### 공통

[0]  README.md 파일을 작성해 주세요.

[0] 마크다운 언어를 숙지하여 작성해 주세요.
[0] 내용은 자유롭게 작성해 주세요.
[0]  본인 브랜치(ex)part1-홍길동)에 스프린트 미션을 업로드해 주세요.

[0]  적절한 커밋 메시지를 남겨 주세요.

[0]  1-Sprint-Mission 레포지토리를 fork 합니다.

[0]  GitHub에 PR(Pull Request)을 생성해 upstream의 본인 브랜치(ex)part1-홍길동)에 미션을 제출합니다.

[0]  PR 코멘트에 아래 내용들을 포함해 주세요.

[0]  스프린트 미션 요구사항 체크리스트

[0]  Git 활용 과정에서 유닉스 커맨드를 활용해 주세요.

[0]  HTML, CSS 파일을 Netlify로 배포합니다. (https://calm-arithmetic-fee968.netlify.app/)

#### 로그인 페이지, 회원가입 페이지 공통

[0] “판다마켓" 로고 클릭 시 루트 페이지(“/”)로 이동합니다.
[0] 로그인 페이지, 회원가입 페이지 모두 로고 위 상단 여백이 동일합니다.
[0] SNS 아이콘들은 클릭 시 각각 “https://www.google.com/”, “https://www.kakaocorp.com/page/” 으로 이동합니다.
[0] input 요소에 focus in 일 때, 테두리 색상은 ##3692FF입니다.
[0] input 요소에 focus out 일 때, 테두리는 없습니다.

#### 로그인 페이지

[0] “회원가입”버튼 클릭 시 “/signup” 페이지로 이동합니다.

#### 회원가입 페이지

[0] “로그인”버튼 클릭 시 “/login” 페이지로 이동합니다

### 심화 요구사항

#### 공통

[0] palette에 있는 color값들을 css 변수로 등록해서 사용합니다.
[0] 구글 애널리틱스로 방문자 수 확인하기 할 수 있도록 설정합니다.

#### 로그인 페이지, 회원가입 페이지 공통

[0] 비밀번호, 비밀번호 확인 input 요소 오른쪽에 비밀번호를 확인할 수 있는 눈 모양 아이콘을 추가합니다.

2024-07-09 16:09 UTC, leejunkoo requested changes
영섭님 수고 많으셨습니다~

1. 중복되는 코드가 너무 많습니다~
폴더별로 분리하신 것은 잘하셨습니다. 그렇지만 폴더 내부에 공통으로 사용되는 코드는 전역적으로 사용할 수 있도록 분리하는 것이 필요해보입니다.
2. 요구사항을 더 꼼꼼히 확인해보시면 좋을 것 같아요~ 아주 약간의 아쉬움이 여러곳에서 보입니다!
3. 이미지 요소의 파일 이름을 더 구체적으로 명시하면 코드를 읽기 편할 것 같습니다. (파일을 확인하지 않더라도 대략적으로 파악이 가능하니까요~)

2024-07-09 16:09 UTC, leejunkoo commented on mission/index.html
1. [title 태그] - 판다마켓 한번 확인해주세요~
2. [header 태그] -  nav 태그를 한번 확인해보세요~ 링크입니다~ https://developer.mozilla.org/ko/docs/Web/HTML/Element/nav
3. [footer] - 화면의 너비가 1920px 보다 작아질 때, 최하단에 있는 “codeit-2024”의 왼쪽 여백 200px과 SNS 아이콘들의 오른쪽 여백 200px을 유지하면서 가운데 있는 “Privacy Policy”, “FAQ” 요소와 각각 동일한 간격을 유지하며 가까워져야 합니다.
위 요구사항이 반영되지 않았어요~
4. [구경하러 가기 버튼] - 이동하는 path를 확인해주세요~

2024-07-12 00:19 UTC, songyoungsub commented on mission/index.html
'중복되는 코드가 너무 많습니다~
폴더별로 분리하신 것은 잘하셨습니다. 그렇지만 폴더 내부에 공통으로 사용되는 코드는 전역적으로 사용할 수 있도록 분리하는 것이 필요해보입니다. '

이 부분 제외 일단 고쳤습니다. 이 부분은  주말에 고쳐서 pr 올리겠습니다

2024-07-12 10:52 UTC, leejunkoo commented on mission/index.html
넵 알겠습니다~ 다음 코드리뷰에서 확인할게요~ 수고 많으셨습니다!

2024-07-12 10:52 UTC, merged