Basic 주영은
codeit-sprint-fullstack/1-Sprint-Mission-FE pull request #3
Opened 2024-07-01 01:23 UTC by juyeongeun

## 요구사항

### 기본

**랜딩 페이지 Mission-01**
- [x]  React와 같은 UI 라이브러리를 사용하지 않고 진행합니다
- [x]  PC사이즈만 고려해 주어진 디자인으로 구현합니다.
- [x]  HTML, CSS 파일을 [Netlify](https://www.netlify.com/)로 배포해 주세요. (참고: https://www.codeit.kr/learn/5309)
- [x]  랜딩 페이지의 url path는 루트(‘/’)로 설정합니다.
- [x]  title은 “판다마켓”로 설정합니다.
- [x]  “판다마켓” 로고 클릭 시 루트 페이지(‘/’)로 이동합니다.
- [x]  '로그인' 버튼 클릭 시 로그인 페이지(‘/login’)로 이동합니다 (빈 페이지)
- [x]  “구경하러 가기”버튼 클릭 시(’/items’)로 이동합니다. (빈 페이지)
- [x]  “Privacy Policy”, “FAQ”는 클릭 시 각각 Privacy 페이지(‘/privacy’), FAQ 페이지(‘/faq’)로 이동합니다.(모두 빈 페이지)
- [x]  페이스북, 트위터, 유튜브, 인스타그램 아이콘을 클릭 시 각각의 홈페이지로 새로운 창이 열리면서 이동합니다.
- [x]  아래로 스크롤해도 “판다 마켓” 로고와 “로그인” 버튼이 있는 상단 내비게이션 바(Global Navigation Bar)가 최상단에 고정되게 해 주세요.
- [x]  화면의 너비가 1920px 이상이면 하늘색 배경색은 너비를 꽉 채우도록 채워지고, 내부 요소들의 위치는 고정되고, 여백만 커지도록 합니다.
- [x]  화면의 너비가 1920px 보다 작아질 때, “판다마켓” 로고의 왼쪽 여백 200px, “로그인" 버튼의 오른쪽 여백 200px이 유지되고, 화면의 너비가 작아질수록 두 요소 간 거리가 가까워지도록 설정합니다.
- [x]  화면의 너비가 1920px 이상이면 내부에 있는 요소 간 동일한 간격을 유지하며 가운데 정렬해야 합니다.
- [x]  화면의 너비가 1920px 보다 작아질 때, 최하단에 있는 “codeit-2024”의 왼쪽 여백 200px과 SNS 아이콘들의 오른쪽 여백 200px을 유지하면서 가운데 있는 “Privacy Policy”, “FAQ” 요소와 각각 동일한 간격을 유지하며 가까워져야 합니다.
- [x]  클릭으로 기능이 동작해야 하는 경우, 사용자가 클릭할 수 있는 요소임을 알 수 있도록 CSS 속성 cursor: pointer로 설정합니다.

**로그인 / 회원가입 Mission-02**
- [x]  README.md 파일을 작성해 주세요.
    - [x] 마크다운 언어를 숙지하여 작성해 주세요.
    - [x] 내용은 자유롭게 작성해 주세요.
- [x]  본인 브랜치(ex)part1-홍길동)에 스프린트 미션을 업로드해 주세요.
- [x]  적절한 커밋 메시지를 남겨 주세요.
- [x]  1-Sprint-Mission 레포지토리를 fork 합니다.
- [x]  GitHub에 PR(Pull Request)을 생성해 upstream의 본인 브랜치(ex)part1-홍길동)에 미션을 제출합니다.
- [x]  PR 코멘트에 아래 내용들을 포함해 주세요.
    - [x]  스프린트 미션 요구사항 체크리스트
        - [x] 아래 예시 사진과 같이 완료한 만큼 체크 표시를 해 주세요. 참고
    - [x]  주요 변경사항
    - [x]  멘토님에게 남길 메시지
- [x]  Git 활용 과정에서 유닉스 커맨드를 활용해 주세요.
- [x]  HTML, CSS 파일을 Netlify로 배포합니다. (참고: https://www.codeit.kr/learn/5309)

**로그인 페이지, 회원가입 페이지 공통**
- [x] “판다마켓" 로고 클릭 시 루트 페이지(“/”)로 이동합니다.
- [x] 로그인 페이지, 회원가입 페이지 모두 로고 위 상단 여백이 동일합니다.
- [x] SNS 아이콘들은 클릭 시 각각 “https://www.google.com/”, “https://www.kakaocorp.com/page/” 으로 이동합니다.
- [x] input 요소에 focus in 일 때, 테두리 색상은 ##3692FF입니다.
- [x] input 요소에 focus out 일 때, 테두리는 없습니다.

**로그인 페이지**
- [x] “회원가입”버튼 클릭 시 “/signup” 페이지로 이동합니다.

**회원가입 페이지**
- [x] “로그인”버튼 클릭 시 “/login” 페이지로 이동합니다.

### 심화

**랜딩 페이지 Mission-01**
- [x]  reset.css를 설정해 주세요.
- [x]  사용자의 브라우저 설정에 따라 기본 폰트 크기 설정이 변화함에 따라서 페이지의 요소 간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정해 주세요.

**로그인 / 회원가입 Mission-02**
- [x] palette에 있는 color값들을 css 변수로 등록해서 사용합니다.
- [x] 사용자의 브라우저가 크고 작아짐에 따라 페이지의 요소 간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정해 주세요.
- [x] 구글 애널리틱스로 방문자 수 확인하기 할 수 있도록 설정합니다.

**로그인 페이지, 회원가입 페이지 공통**
- [x] 비밀번호, 비밀번호 확인 input 요소 오른쪽에 비밀번호를 확인할 수 있는 눈 모양 아이콘을 추가합니다.

## 스크린샷

![image](/image/index_html.png)
![image](/image/login_html.png)
![image](/image/signup_html.png)

## 멘토에게
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.
- 미디어 쿼리를 사용해서 <<사용자의 브라우저 설정에 따라 기본 폰트 크기 설정이 변화함에 따라서 페이지의 요소 간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정해 주세요.>> 구현하는 방법이 이해하기 어렵습니다.

2024-07-09 03:44 UTC, leejunkoo commented
영은님 수고 많으셨습니다!

2번째 질문하셨던 미디어 쿼리를 사용해서 <<사용자의 브라우저 설정에 따라 기본 폰트 크기 설정이 변화함에 따라서 페이지의 요소 간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정해 주세요.>> 구현하는 방법이 이해하기 어렵습니다. 요구사항 수정한 건 '브라우저 내에서 확대/축소 변경시 폰트와 요소들의 크기가 바뀌도록' 이라고 해서 따로 수정한 건 없는데 해상도가 변경될 때 재배치 하는 것이 궁금합니다.

이 부분은 css-rem을 사용해서 잘 구현하신 것 같아요. 동작을 확인하는 방법은 크롬브라우저에서 [Settings -> Apperance -> Font size]를 수정해보시면 화면이 대응하는 것을 확인하실 수 있습니다! 잘 하셨어요~

2024-07-09 12:39 UTC, leejunkoo requested changes
코멘트 남긴 부분 확인해주세요~

path 이동시 html이 앞에 붙는 경우도 확인해주세요!

2024-07-09 16:44 UTC, leejunkoo reviewed
추가내용입니다~

2024-07-09 16:44 UTC, leejunkoo commented on style/loginstyle.css
1. 중복된 클래스들이 보입니다.
2. .show, .non-show 의도에 맞는 이름이면 더 알기 쉬울 것 같아요.

2024-07-09 16:44 UTC, leejunkoo commented on style/signupstyle.css
1. .show, .non-show, .show-check, .non-show-check 의도에 맞는 클래스명을 가지면 좋을 것 같습니다~ 혹은, 하나의 클래스로 지정하고 엘리멘트가 여러개의 클래스명을 갖도록 하는 것도 좋아보여요~

2024-07-11 12:04 UTC, juyeongeun commented on js/login.js
js 파일과 미디어쿼리 부분은 미션3 내용이었습니다! 미션 1+2 브랜치에 바로 push 해서 합쳐서 올라가졌어요🥲

2024-07-12 00:17 UTC, juyeongeun commented on js/signup.js
수정했습니다!

2024-07-12 00:17 UTC, juyeongeun commented on style/loginstyle.css
수정했습니다!

2024-07-12 00:17 UTC, juyeongeun commented on style/signupstyle.css
수정했습니다!

2024-07-12 10:51 UTC, merged