Basic-박명준 (PR)
codeit-sprint-fullstack/1-Sprint-Mission-FE pull request #6
Opened 2024-07-01 07:54 UTC by parkmyungjun

## 요구사항

### 기본 요구사항
> **Sprint Mission 1**

**<랜딩 페이지>**

- [x]  React와 같은 UI 라이브러리를 사용하지 않고 진행합니다
- [x]  PC사이즈만 고려해 주어진 디자인으로 구현합니다.
- [x]  HTML, CSS 파일을 Netlify로 배포해 주세요. (참고: https://www.codeit.kr/learn/5309)
- [x]  랜딩 페이지의 url path는 루트(‘/’)로 설정합니다.
- [x]  title은 “판다마켓”로 설정합니다.
- [x]  “판다마켓” 로고 클릭 시 루트 페이지(‘/’)로 이동합니다.
- [x]  '로그인' 버튼 클릭 시 로그인 페이지(‘/login’)로 이동합니다 (빈 페이지)
- [x]  “구경하러 가기”버튼 클릭 시(’/items’)로 이동합니다. (빈 페이지)
- [x]  “Privacy Policy”, “FAQ”는 클릭 시 각각 Privacy 페이지(‘/privacy’), FAQ 페이지(‘/faq’)로 이동합니다.(모두 빈 페이지)
- [x]  페이스북, 트위터, 유튜브, 인스타그램 아이콘을 클릭 시 각각의 홈페이지로 새로운 창이 열리면서 이동합니다.
- [x]  아래로 스크롤해도 “판다 마켓” 로고와 “로그인” 버튼이 있는 상단 내비게이션 바(Global Navigation Bar)가 최상단에 고정되게 해 주세요.
- [x]  화면의 너비가 1920px 이상이면 하늘색 배경색은 너비를 꽉 채우도록 채워지고, 내부 요소들의 위치는 고정되고, 여백만 커지도록 합니다.
- [x]  화면의 너비가 1920px 보다 작아질 때, “판다마켓” 로고의 왼쪽 여백 200px, “로그인" 버튼의 오른쪽 여백 200px이 유지되고, 화면의 너비가 작아질수록 두 요소 간 거리가 가까워지도록 설정합니다.
- [x]  화면의 너비가 1920px 이상이면 내부에 있는 요소 간 동일한 간격을 유지하며 가운데 정렬해야 합니다.
- [x]  화면의 너비가 1920px 보다 작아질 때, 최하단에 있는 “codeit-2024”의 왼쪽 여백 200px과 SNS 아이콘들의 오른쪽 여백 200px을 유지하면서 가운데 있는 “Privacy Policy”, “FAQ” 요소와 각각 동일한 간격을 유지하며 가까워져야 합니다.
- [x]  클릭으로 기능이 동작해야 하는 경우, 사용자가 클릭할 수 있는 요소임을 알 수 있도록 CSS 속성 cursor: pointer로 설정합니다.

> **Sprint Mission 2**

**<공통>**
- [x]  README.md 파일을 작성해 주세요.
  - [x] 마크다운 언어를 숙지하여 작성해 주세요.
  - [x] 내용은 자유롭게 작성해 주세요.
- [x]  본인 브랜치(ex)part1-홍길동)에 스프린트 미션을 업로드해 주세요.
- [x]  적절한 커밋 메시지를 남겨 주세요.
- [x]  1-Sprint-Mission 레포지토리를 fork 합니다.
- [x]  GitHub에 PR(Pull Request)을 생성해 upstream의 본인 브랜치(ex)part1-홍길동)에 미션을 제출합니다.
- [x]  PR 코멘트에 아래 내용들을 포함해 주세요.
  - [x]  스프린트 미션 요구사항 체크리스트
    - [x] 아래 예시 사진과 같이 완료한 만큼 체크 표시를 해 주세요. 참고
  - [x]  주요 변경사항
  - [x]  멘토님에게 남길 메시지
- [x]  Git 활용 과정에서 유닉스 커맨드를 활용해 주세요.
- [x]  HTML, CSS 파일을 Netlify로 배포합니다. (참고: https://www.codeit.kr/learn/5309)

**<로그인 페이지, 회원가입 페이지 공통>**

- [x] “판다마켓" 로고 클릭 시 루트 페이지(“/”)로 이동합니다.
- [x] 로그인 페이지, 회원가입 페이지 모두 로고 위 상단 여백이 동일합니다.
- [x] SNS 아이콘들은 클릭 시 각각 “https://www.google.com/”, “https://www.kakaocorp.com/page/” 으로 이동합니다.
- [x] input 요소에 focus in 일 때, 테두리 색상은 ##3692FF입니다.
- [x] input 요소에 focus out 일 때, 테두리는 없습니다.

**<로그인 페이지>**

- [x] “회원가입”버튼 클릭 시 “/signup” 페이지로 이동합니다.

**<회원가입 페이지>**

- [x] “로그인”버튼 클릭 시 “/login” 페이지로 이동합니다
***
### 심화 요구사항
> **Sprint Mission 1**

**<공통>**
- [x] reset.css를 설정해 주세요.
- [x] 사용자의 브라우저 설정에 따라 기본 폰트 크기 설정이 변화함에 따라서 페이지의 요소 간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정해 주세요.

> **Sprint Mission 2**

**<공통>**

- [x] palette에 있는 color값들을 css 변수로 등록해서 사용합니다.
- [x] 사용자의 브라우저가 크고 작아짐에 따라 페이지의 요소 간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정해 주세요.
- [x] 구글 애널리틱스로 방문자 수 확인하기 할 수 있도록 설정합니다.

**<로그인 페이지, 회원가입 페이지 공통>**

- [x] 비밀번호, 비밀번호 확인 input 요소 오른쪽에 비밀번호를 확인할 수 있는 눈 모양 아이콘을 추가합니다.

## 주요 변경사항
- 랜딩 페이지 제작 (Sprint Mission 1)
- 로그인 페이지, 회원가입 페이지 추가 (Sprint Mission 2)

## 스크린샷
![image](https://github.com/parkmyungjun/1-Sprint-Mission-FE/blob/main/images/main-page.png?raw=true)
***
![image](https://github.com/parkmyungjun/1-Sprint-Mission-FE/blob/main/images/login-page.png?raw=true)
***
![image](https://github.com/parkmyungjun/1-Sprint-Mission-FE/blob/main/images/signup-page.png?raw=true)

## 사이트 링크
[판다 마켓](https://pandamarket2.netlify.app)

## 멘토에게
- `"사용자의 브라우저가 크고 작아짐에 따라 페이지의 요소 간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정"` -> 감이 안잡힙니다.
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-07-09 04:11 UTC, leejunkoo commented
명준님 수고 많으셨습니다~

간단한 형태로 구현하셨네요~ 
앞으로 수업을 따라가시면서 미션 프로젝트가 고도화가 될것 같네요. 
파일을 분리해서 관리하는 형태도 좋을것 같습니다~

질문해주셨던

"사용자의 브라우저가 크고 작아짐에 따라 페이지의 요소 간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정" -> 감이 안잡힙니다.

이 부분은 너비값이나 높이값을 %, vh, vw등의 형태로 사용해보라는 의미 같습니다. 
https://developer.mozilla.org/ko/docs/Learn/CSS/Building_blocks/Values_and_units
위 링크 한번 확인해보시면 좋을것 같아요~

2024-07-09 12:40 UTC, leejunkoo requested changes
코멘트 확인해주세요~

2024-07-09 16:45 UTC, leejunkoo reviewed
이름을 통해 이미지 요소들을 알 수 있도록 이름을 변경하는 것이 좋아보입니다!

2024-07-09 16:45 UTC, leejunkoo commented on images/Component 2.png
1. 이름으로 이미지를 알 수 있도록 수정해주세요~

2024-07-09 16:45 UTC, leejunkoo commented on images/Component 3.png
1. 이름으로 이미지를 알 수 있도록 수정해주세요~

2024-07-09 16:45 UTC, leejunkoo commented on style/sign-in-up.css
1. 로그인과 회원가입에서 공통으로 사용되는 css코드와 각각 다르게 사용하는 css코드를 분리하는 편이 좋아보입니다.

2024-07-09 16:45 UTC, leejunkoo commented on index.html
1. 시맨틱 태그를 사용하는 것을 권장드립니다~ 아래 링크를 참조해 주세요.
https://developer.mozilla.org/ko/docs/Glossary/Semantics

2024-07-11 02:25 UTC, mjpark-k commented on page/login.html
먼저 const로 구분해서 사용했으며 기존에 html파일에 있던 js 코드를 파일로 분리하였습니다.
눈모양 아이콘의 차별을 두기 위해 password type일 때는 show icon을 넣고, text type일 때는 close icon을 넣어 구분하였습니다. 그리고 기능적으로 input에 value값이 있을 때 icon이 보이도록 추가했습니다!!
리뷰해주셔서 감사합니다 😊 👍

2024-07-11 02:25 UTC, mjpark-k commented on page/signup.html
js 코드를 파일로 따로 분리했습니다!

2024-07-11 02:26 UTC, mjpark-k commented on images/Component 2.png
구분이 어려운 부분이 있는 이미지 이름은 구분이 가능하게 변경했습니다!!

2024-07-11 02:26 UTC, mjpark-k commented on images/Component 3.png
구분이 어려운 부분이 있는 이미지 이름은 구분이 가능하게 변경했습니다!!

2024-07-11 02:27 UTC, mjpark-k commented on style/sign-in-up.css
이렇게 분리하는 게 맞는지는 모르겠지만...
최대한 공통된 부분을 common.css에 묶고, 따로 sign-up에 필요한 style 들은 sign-up-only.css에 분리해봤습니다!!!

2024-07-11 02:28 UTC, mjpark-k commented on index.html
수정하였습니다!!

2024-07-11 02:41 UTC, mjpark-k commented on page/login.html
아 그리고 저번 미션 과제인 google Analytics 미션을 PR 올릴 때, 수행했었는데 자료를 깜빡하고 올리지 못했네요... 죄송합니다. 그래서 스크린샷 첨부해서 수정하였습니다!!!

2024-07-11 11:15 UTC, leejunkoo approved these changes
와우 명준님~ 너무 수고 많으셨습니다! 코드가 훨씬 좋아졌어요!!

더 잘해지시길 바라는 마음에서 몇가지만 말씀드리면서 머지하겠습니다!

1. img_home_*.png - 더 구체적인 파일 이름! (파일 이름만 봐도 알 수 있어야 좋습니다~)
2. 판다 얼굴.png - 파일 이름은 한글보다는 영어를 사용하시길 바랍니다! 인코딩 문제로 오류가 발생할 수 있어요~
2. js와 css 잘 분리하셨습니다.

너무 수고 많으셨습니다!

2024-07-11 11:15 UTC, merged