[김민수] sprint 5
codeit-sprint-fullstack/1-Sprint-Mission-FE pull request #76
Opened 2024-07-29 00:44 UTC by Minsugar98

# 요구사항
-  기본 요구사항
-  공통

-  [x] Github에 스프린트 미션 PR을 만들어 주세요.
-  [x] React를 사용해 진행합니다.
## 중고마켓 페이지

-  [x]  PC, Tablet, Mobile 디자인에 해당하는 중고마켓 페이지를 만들어 주세요.

-  [x]  중고마켓 페이지 url path는 별도로 설정하지 않고, ‘/’에 보이도록 합니다.

-  [x]  상품 데이터는 [https://panda-market-api.vercel.app/docs/](https://panda-market-api.vercel.app/docs/#/)에 명세된 GET 메소드 “/products” 를 사용해주세요.

-  [x]  상단 네비게이션 바, 푸터는 랜딩 페이지와 동일한 스타일과 규칙으로 만들어주세요.

-  [x]  상품 데이터는 [https://panda-market-api.vercel.app/docs/](https://panda-market-api.vercel.app/docs/#/)에 명세된 GET 메소드 “/products” 를 활용해주세요.

-  [x] 상품 목록 페이지네이션 기능을 구현합니다.
-  [x] 드롭 다운으로 “최신 순” 또는 “좋아요 순”을 선택해서 정렬을 구현하세요.
-  [x] 상품 목록 검색 기능을 구현합니다.
-  [x]  베스트 상품 데이터는 [https://panda-market-api.vercel.app/docs/](https://panda-market-api.vercel.app/docs/#/)에 명세된 GET 메소드 “/products”의 정렬 기준 favorite을 사용해주세요.

## 심화 요구사항
-  공통

-  [x] 커스텀 hook을 만들어 필요한 곳에 활용해 보세요.
중고마켓 페이지

-  [x] 중고 마켓의 카드 컴포넌트 반응형 기준은 다음과 같습니다.
## 베스트 상품
-  Desktop : 4열
-  Tablet : 2열
-  Mobile : 1열
## 전체 상품
-  Desktop : 5열
-  Tablet : 3열
-  Mobile : 2열
## 페이지 네이션 기능을 구현합니다.
- 반응형으로 보여지는 물품들의 개수를 다르게 설정할때 서버에 보내는 pageSize값을 적절하게 설정합니다.

## 스크린샷
![image](https://github.com/user-attachments/assets/0ce489c3-4513-48fd-8bef-92dfd5d2bc4d)
![image](https://github.com/user-attachments/assets/9a38dff4-2d41-4428-ae35-cc2c484a944e)
![image](https://github.com/user-attachments/assets/f65e9666-4a1d-419f-a8f5-d98afe9b9366)

## 멘토에게
- 코드를 작성하다 보니 useEffect, useState가 많아진 느낌인데 필요한 내용만 적어놓고변경 값에에 대해관리해야 하는 건가요 ??
- 기능을 구현하면서 git commit 내용을 남기려고했지만…. 반복적으로 git commit 내용작성하는 게 쉽지지않네요. (매번 까먹어요)

2024-07-31 14:21 UTC, wildCodingWarrior requested changes
일단 gitignore로 node_modules 없애기부터 해야겠습니다.
https://zel0rd.tistory.com/140
이거 참고해서 없애보시고, 잘 안되면 내일 저녁에 멘토링 하면서 같이 해봅시다.

Prettier도 혹시 아직 설치 안하셨으면 같이 설치하는 게 좋겠네요.

2024-07-31 14:21 UTC, wildCodingWarrior commented on src/main.js
> +  const [ValueItem, setValueItem] = useState({list:[]}) //get API
camelCase 사용해주세요~

2024-07-31 14:21 UTC, wildCodingWarrior commented on src/main.js
> +    };
cleanup 좋습니다

2024-07-31 14:21 UTC, wildCodingWarrior commented on .gitignore
> +node_modules
아마 이미 올라간 node_modules는 삭제가 안되어서 안될수도 있고, node_modules/로 바꿔야할 수도 있겠습니다.

2024-07-31 14:21 UTC, wildCodingWarrior commented on src/main.js
> +  }, []);
api 폴더 만들어서 따로 관리해주는게 좋습니다. 이렇게 클라리언트 외부랑 소통하는 모든 경우 (인터페이스겠죠?)에는 따로 관리하는 습관을 가지는 게 좋습니다.

2024-07-31 14:21 UTC, wildCodingWarrior commented on src/main.js
> +            // 페이지 수가 5를 초과할 때는 버튼을 제한
이정도 로직을 JSX에서 그대로 구현하시는 것 보다는, 새로운 컴포넌트를 만드는 편이 더 괜찮겠습니다.

2024-07-31 14:21 UTC, wildCodingWarrior commented on src/main.js
> +            // 페이지 수가 5를 초과할 때는 버튼을 제한
전체적으로 이 부분은 각 컴포넌트 별로 다 나누는게 좋겠어요

2024-07-31 23:56 UTC, Minsugar98 commented on src/main.js
> +  const [ValueItem, setValueItem] = useState({list:[]}) //get API
const [valueItem, setValueItem] 변경했습니다.

감사합니다.

2024-07-31 23:57 UTC, Minsugar98 commented on .gitignore
> +node_modules
이전에도 동일한 문제점이 있었는데
https://zel0rd.tistory.com/140
링크를 통해서 해결했습니다. 감사합니다!

2024-08-01 00:00 UTC, Minsugar98 commented on src/main.js
> +  }, []);
제가 최대한 따로 파일을 분리해서 코드를 작성해 보려고 했지만, 한 코드에서 작성하는 게 편한데, 혹시 한 코드에서 작성을 다 하고 코드를 분리하는 경우도 있나요??

2024-08-01 06:38 UTC, wildCodingWarrior commented on src/main.js
> +  }, []);
보통은 처음부터 나눠서 하고는 합니다.

우리 스프린트 실습 코드가 복잡하지 않고 간단한 편이라서 아직은 이렇게 해도 무방합니다. 그런데 스프린트4에서 CRUD를 전부 했던 것들 감안하면, 혹시 API 주소가 변경되거나, 관련 코드를 찾아보거나 했을 때 분리해두면 훨씬 유지보수가 간단하겠죠?

2024-08-01 07:43 UTC, Minsugar98 commented on src/main.js
> +  }, []);
넵 감사합니다

2024-08-06 17:34 UTC, wildCodingWarrior requested changes
주강사님이 알려주시는 베스트 케이스를 많이 참고하면 좋겠습니다.

지금 의존하기를 권장하지는 않으나, 아래 링크를 참고하는 것도 좋겠습니다.
https://cheatsheets.shecodes.io/react

2024-08-06 17:34 UTC, wildCodingWarrior commented on src/app.js
> +export default App
전반적으로 Prettier를 한 번 적용하면 좋겠네요. Headers 이름도 Header로 합시다.

2024-08-06 17:34 UTC, wildCodingWarrior commented on src/header.css
> +}
header_my_img 이런 방식은 보통 파이썬에서 많이 쓰는 컨벤션입니다. header-my-img 이렇게 하면 좋겠네요. selector에는 kebab-case를 사용합니다.

2024-08-06 17:34 UTC, wildCodingWarrior commented on src/header.js
> +
기존 Landing Page랑 스타일이 조금 다릅니다.

2024-08-06 17:34 UTC, wildCodingWarrior commented on src/header.js
> +import Header_my from './img/Header_my.svg'
_대신 HeaderLogo, 이런식으로 컴포넌트의 컨벤션을 지켜줍시다.

2024-08-06 17:34 UTC, wildCodingWarrior commented on src/index.js
> +);
ReactDOM 사용 방식이 react 18 버전 이전 방식으로 사용하네요.
![image](https://github.com/user-attachments/assets/e5f7799c-7ba9-43a8-bdf2-d66fb636505b)
이걸 참고해봅시다.

2024-08-06 17:34 UTC, wildCodingWarrior commented on src/main.js
> +
이런식으로 addEventListener를 사용하지 않고, 곧바로 JSX 부분에 onClick을 다는 방식이 일반적입니다. 더 React 스럽다고 이야기해도 좋겠네요.

2024-08-07 05:43 UTC, Minsugar98 commented on src/main.js
> +
넵!
시도 해보겠습니다.

2024-08-07 05:44 UTC, Minsugar98 commented on src/header.js
> +
찾아보겠습니다!

2024-08-08 07:58 UTC, merged