[안재민] sprint5
codeit-sprint-fullstack/1-Sprint-Mission-FE pull request #88
Opened 2024-07-30 12:46 UTC by mini-1018

## 요구사항

### 기본

공통

- [x] Github에 스프린트 미션 PR을 만들어 주세요.
- [x] React를 사용해 진행합니다.

중고마켓 페이지

- [ ]  PC, Tablet, Mobile 디자인에 해당하는 중고마켓 페이지를 만들어 주세요.
- [ ]  중고마켓 페이지 url path는 별도로 설정하지 않고, ‘/’에 보이도록 합니다.
- [x]  상품 데이터는 [https://panda-market-api.vercel.app/docs/](https://panda-market-api.vercel.app/docs/#/)에 명세된 GET 메소드 “/products” 를 사용해주세요.
- [ ]  상단 네비게이션 바, 푸터는 랜딩 페이지와 동일한 스타일과 규칙으로 만들어주세요.
- [x]  상품 데이터는 [https://panda-market-api.vercel.app/docs/](https://panda-market-api.vercel.app/docs/#/)에 명세된 GET 메소드 “/products” 를 활용해주세요.
- [x] 상품 목록 페이지네이션 기능을 구현합니다.
- [x] 드롭 다운으로 “최신 순” 또는 “좋아요 순”을 선택해서 정렬을 구현하세요.
- [ ] 상품 목록 검색 기능을 구현합니다.
- [x]  베스트 상품 데이터는 [https://panda-market-api.vercel.app/docs/](https://panda-market-api.vercel.app/docs/#/)에 명세된 GET 메소드 “/products”의 정렬 기준 favorite을 사용해주세요.

### 심화

공통
- [ ] 커스텀 hook을 만들어 필요한 곳에 활용해 보세요.
중고마켓 페이지

- [ ] 중고 마켓의 카드 컴포넌트 반응형 기준은 다음과 같습니다.
베스트 상품
Desktop : 4열
Tablet : 2열
Mobile : 1열
전체 상품
Desktop : 5열
Tablet : 3열
Mobile : 2열
페이지 네이션 기능을 구현합니다.
반응형으로 보여지는 물품들의 개수를 다르게 설정할때 서버에 보내는 pageSize값을 적절하게 설정합니다.

## 주요 변경사항
- 맨 마지막 페이지 버튼 구현 거의 완성하였으나 최신순, 좋아요순 온클릭 이벤트 시, 정렬되고 1페이지로 이동하게 하려합니다.
- 검색은 해당 페이지 10개에서만 검색이 되어서 보완하겠습니다.
- 상품 텍스트 및 버튼 css 미완성

## 스크린샷

![image](이미지url)

## 멘토에게
- useState, useEffect 등을 사용하였지만 렌더링 순서, 연관 등에 따라 재렌더링이 일어나는줄도 모르고 사용했던 것 같습니다. 아직 정확한 개념이 잡히지 않아 걱정입니다. 특히 검색기능 구현할 때 인풋의 e.target.value를 useState setter함수로 관리하려했는데 console.log로 확인해보니 인풋에 아이패드라고 검색했을 때 console.log에는 아이패ㄷ 까지만 되는 문제가 있었습니다. 강사님께 질문도 했지만 아직 정확하게 이해가 가지않습니다.
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-07-31 14:11 UTC, wildCodingWarrior requested changes
node modules는 무슨일이 있어도 git에 올리면 안됩니다! 
https://zel0rd.tistory.com/140
이거 참고해서 지우고 gitignore에서도 추가해주세요~

파일이나 폴더가 조금 꼬여있는 것 같은데, 내일 멘토링 한 이후에는 CRA에 대해서 이해도가 올라간 상태이시니 꼭 하실 수 있을 거라고 믿습니다. 

그리고 커밋이 조금 꼬인것 같은데 안쓰는 파일들도 한번 다 지워봅시다.

2024-07-31 14:11 UTC, wildCodingWarrior commented on react/src/index.js
> +);
이건 따로 App.js 만들어서 거기에서 관리하는게 좋겠습니다.

2024-07-31 14:11 UTC, wildCodingWarrior commented on react/src/api.js
> +  const oderSize = `pageSize=${pageSize}`;
오타입니다

2024-07-31 14:11 UTC, wildCodingWarrior commented on react/src/api.js
> +}
좋네요. 다만 ?${} 이런식으로 안하고 
```
const params = {orderPage: page, pageSize: pageSize, order: orderBy}
const response = await axios.get(
    `https://panda-market-api.vercel.app/products`, { params });
```

이게 더 깔끔해보이지 않나요?

2024-07-31 14:11 UTC, wildCodingWarrior commented on react/src/api.js
> +    `https://panda-market-api.vercel.app/products`
또 동일한 axios 사용하니 instance 만들어서 사용하면 좋겠군요.

2024-07-31 14:11 UTC, wildCodingWarrior commented on react/src/component/Dropdown.js
> +  );
class에는 camelCase보다는 kebab-case가 훨씬 일반적입니다.

2024-08-06 18:53 UTC, wildCodingWarrior requested changes
코드를 아주 깔끔하고 잘 작성하셨습니다.

```
저번 리뷰 이후로 반응형구현, 맨 아래 판매중인 상품 페이지 < 1~5 > 버튼 구현하였습니다. 다 완성하고나서 검색 인풋이 자꾸 초기화 되는현상이 발생했습니다. 재렌더링 될만한 코드들을 재차 확인하였지만 이유를 찾지 못했습니다. 결국 구글링 중 useRef 활용하여 구현하였습니다. 이유를 꼭 알고싶습니다.
(기존에는 e.target.value 이용하였고 인풋에 onChange 이벤트로 관리하였습니다.)
(초기화 현상 : 인풋 입력 시 입력이 안되거나 또는 한글자 입력되더라도 그 다음 글자 입력시 초기화, console.log(e.target.value)로 확인하여도 1번 찍히고 다시 초기화)
```

이 질문에 대한 답변은, 재렌더링으로 인해서 발생한 것입니다.

MobileResponsive, PcAndTabletResponsive 이 두 컴포넌트가 ForSaleItems 컴포넌트가 렌더링 될 때마다 새롭게 재 생성되어 발생한 문제입니다. 두 컴포넌트를 컴포넌트 밖으로 빼서 만들어보세요.

2024-08-06 18:53 UTC, wildCodingWarrior commented on src/component/pageButton.js
> +import { useEffect, useState } from 'react';
파일 이름이 pageButton이 아니라 PageButton이어야합니다.

2024-08-06 18:53 UTC, wildCodingWarrior commented on src/App.test.js
> +// });
아얘 삭제해도 좋겠군요

2024-08-06 18:53 UTC, wildCodingWarrior commented on src/api.js
> +}
query를 만들어 사용한 방식도 좋지만, params object를 만들어 보내는 것도 좋습니다.

https://axios-http.com/kr/docs/req_config
이거 참고해보세요.

2024-08-06 18:53 UTC, wildCodingWarrior commented on src/hooks/useResponsive.js
> +};
커스텀 훅 아주 깔끔하게 잘 사용하셨네요!

2024-08-06 18:53 UTC, wildCodingWarrior commented on src/component/Items.js
> +  }, [isTablet, isMobile]);
구조가 아주 깔끔합니다.

2024-08-06 18:53 UTC, wildCodingWarrior commented on src/component/Items.js
> +    <div className="best-items-containor">
containor는 오타네요

2024-08-08 00:04 UTC, mini-1018 commented on src/component/Items.js
> +    <div className="best-items-containor">
감사합니다. 오타 수정 완료입니다!

2024-08-08 01:21 UTC, mini-1018 commented on src/component/pageButton.js
> +import { useEffect, useState } from 'react';
수정완료입니다!

2024-08-08 08:28 UTC, mini-1018 commented on src/api.js
> +}
수정완료했고 컴포넌트에서도   
    const items = await getItems({ page: 1, pageSize: itemsPerPage });
이런식으로 수정완료했습니다!

2024-08-08 12:59 UTC, wildCodingWarrior commented on src/api.js
> +}
Push만 해주시면 merge 할게요

2024-08-08 13:58 UTC, merged